
if (!require(udpipe)) {install.packages("udpipe")};  library(udpipe)
if (!require(dplyr)) {install.packages("dplyr")};  library(dplyr)
if (!require(ggplot2)) {install.packages("ggplot2")};  library(ggplot2)
if (!require(stopwords)) {install.packages("stopwords")};  library(stopwords)
if (!require(shinyWidgets)) {install.packages("shinyWidgets")};  library(shinyWidgets)
if (!require(shinydashboard)) {install.packages("shinydashboard")};  library(shinydashboard)
if(!require(lattice)){install.packages('lattice')};library(lattice)
if (!require(shiny)) {install.packages("shiny")};  library(shiny)
if (!require(stringr)) {install.packages("stringr")};  library(stringr)
if (!require(tm)) {install.packages("tm")};  library(tm)
if (!require(markdown)) {install.packages("markdown")};  library(markdown)
if (!require(quanteda)) {install.packages("quanteda")};  library(quanteda)
if (!require(tools)) {install.packages("tools")};  library(tools)
if (!require(ggraph)) {install.packages("ggraph")};  library(ggraph)
if (!require(igraph)) {install.packages("igraph")};  library(igraph)
if (!require(DT)) {install.packages("DT")};  library(DT)
if (!require(tidytext)) {install.packages("tidytext")};  library(tidytext)

